# SPDX-License-Identifier: GPL-2.0
dtb-y += kvim4n.dtb
dtb-y += kvim4.dtb
dtb-y += kvim3.dtb
dtb-y += kvim3l.dtb
dtb-y += kvim1s.dtb
# TVPro variants (T7/T7C with 4G/8G DDR)
dtb-y += t7_a311d2_tvpro4g.dtb
dtb-y += t7_a311d2_tvpro8g.dtb
dtb-y += t7c_a311d2_tvpro4g.dtb
dtb-y += t7c_a311d2_tvpro8g.dtb
# Debian variants
dtb-y += t7_a311d2_tvpro4gdebian.dtb
dtb-y += t7_a311d2_tvpro8gdebian.dtb
dtb-y += t7c_a311d2_tvpro4gdebian.dtb
dtb-y += t7c_a311d2_tvpro8gdebian.dtb
