# SPDX-License-Identifier: GPL-2.0
dtb-y += t7c_kvim4n.dtb
dtb-y += t7_kvim4.dtb
dtb-y += g12b_kvim3.dtb
dtb-y += sm1_kvim3l.dtb
dtb-y += s4_kvim1s.dtb
# TVPro variants (T7/T7C with 4G/8G DDR)
dtb-y += t7_a311d2_tvpro4g.dtb
dtb-y += t7_a311d2_tvpro8g.dtb
dtb-y += t7c_a311d2_tvpro4g.dtb
dtb-y += t7c_a311d2_tvpro8g.dtb
