/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 * Copyright (c) 2026 CoreLab.
 */

#ifndef __T7_DISPLAY_CLKC_H
#define __T7_DISPLAY_CLKC_H

/*
 * Sparse IDs mirror the vendor amlogic,t7-clkc.h values for the display
 * clocks needed by the forward-ported T7 DRM/VPU/HDMITX path.
 */
#define CLKID_T7_DISPLAY_HDMITX_SYS_MUX		128
#define CLKID_T7_DISPLAY_HDMITX_SYS_DIV		129
#define CLKID_T7_DISPLAY_HDMITX_SYS		130

#define CLKID_T7_DISPLAY_VID_LOCK_DIV		165
#define CLKID_T7_DISPLAY_VID_LOCK		166

#define CLKID_T7_DISPLAY_VPU_0_MUX		177
#define CLKID_T7_DISPLAY_VPU_0_DIV		178
#define CLKID_T7_DISPLAY_VPU_0			179
#define CLKID_T7_DISPLAY_VPU_1_MUX		180
#define CLKID_T7_DISPLAY_VPU_1_DIV		181
#define CLKID_T7_DISPLAY_VPU_1			182
#define CLKID_T7_DISPLAY_VPU			183
#define CLKID_T7_DISPLAY_VPU_CLKB_TMP_MUX	184
#define CLKID_T7_DISPLAY_VPU_CLKB_TMP_DIV	185
#define CLKID_T7_DISPLAY_VPU_CLKB_TMP		186
#define CLKID_T7_DISPLAY_VPU_CLKB_DIV		187
#define CLKID_T7_DISPLAY_VPU_CLKB		188
#define CLKID_T7_DISPLAY_VPU_CLKC_P0_MUX	189
#define CLKID_T7_DISPLAY_VPU_CLKC_P0_DIV	190
#define CLKID_T7_DISPLAY_VPU_CLKC_P0		191
#define CLKID_T7_DISPLAY_VPU_CLKC_P1_MUX	192
#define CLKID_T7_DISPLAY_VPU_CLKC_P1_DIV	193
#define CLKID_T7_DISPLAY_VPU_CLKC_P1		194
#define CLKID_T7_DISPLAY_VPU_CLKC_MUX		195
#define CLKID_T7_DISPLAY_VAPB_0_MUX		196
#define CLKID_T7_DISPLAY_VAPB_0_DIV		197
#define CLKID_T7_DISPLAY_VAPB_0		198
#define CLKID_T7_DISPLAY_VAPB_1_MUX		199
#define CLKID_T7_DISPLAY_VAPB_1_DIV		200
#define CLKID_T7_DISPLAY_VAPB_1		201
#define CLKID_T7_DISPLAY_VAPB			202

#define CLKID_T7_DISPLAY_HDMITX_PRIF_MUX	342
#define CLKID_T7_DISPLAY_HDMITX_PRIF_DIV	343
#define CLKID_T7_DISPLAY_HDMITX_PRIF		344
#define CLKID_T7_DISPLAY_HDMITX_200M_MUX	345
#define CLKID_T7_DISPLAY_HDMITX_200M_DIV	346
#define CLKID_T7_DISPLAY_HDMITX_200M		347

#define NR_T7_DISPLAY_CLKS			348

#endif /* __T7_DISPLAY_CLKC_H */
